### ISSUE TITLE
SessionID

### ISSUE THREAD

**Issue by williamgeurts** [peet47/hassio_kia#1]
Hi,
Good work, thanks for that. I don't understand how I get the SessionID. Instructions: You have to login to the service and extract the SessionID and enter into the script. Login via the APP doesn't give me a SessionID, and I don't have another login account. Can you help me?

**Comment by peet47** [comment]
HI,

you first have to login here:
https://www.kia.com/nl/mijnkia/

after the succesfull login go to the devlopertools in the browser, for example in chrome its the 3 dots (in the right corner) -> more tools -> developer tools.

Then go to Application -> Cookies -> and click on the kia website. In this tab you will see all Cookies and also the ASP.NET_SessionId 

Hope this helps.

**Comment by peet47** [comment]
solved
